# Generated by Django 4.0.2 on 2025-06-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('race', 'name')},
        ),
    ]
