# Generated by Django 4.0.2 on 2025-06-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_skill_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bio',
            field=models.TextField(),
        ),
    ]
